{"kind":"symbol","identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"content":[{"text":"Overview","type":"heading","anchor":"Overview","level":2},{"inlineContent":[{"type":"image","identifier":"Logo.png"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"LicenseKit lets you protect your software with commercial licenses on most Apple platforms (iOS, macOS, tvOS, watchOS, & visionOS)."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"LicenseKit lets you define licenses with code, read licenses from files, validate licenses from an API, integrate with external services like Gumroad, etc. It can validate expiration date, platform, bundle ID, tier, environment, features, and much more."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"LicenseKit lets you cache licenses to handle temporary connectivity loss, and use service proxying to combine multiple data sources."}],"type":"paragraph"},{"text":"Installation","level":2,"type":"heading","anchor":"Installation"},{"inlineContent":[{"type":"text","text":"LicenseKit can be installed with the Swift Package Manager:"}],"type":"paragraph"},{"type":"codeListing","code":["https:\/\/github.com\/Kankoda\/LicenseKit.git"],"syntax":null},{"text":"Getting Started","level":2,"type":"heading","anchor":"Getting-Started"},{"type":"paragraph","inlineContent":[{"text":"In LicenseKit, a ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference","isActive":true},{"text":" is used to manage product licenses. Use ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"your"}]},{"type":"text","text":" LicenseKit license key to create a "},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference"},{"type":"text","text":" instance with the license services that you want to use to access your product licenses, for instance:"}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(licenseKey: \"your-license-key\") {","    .binary(","        licenses: [","            License(licenseKey: \"license-key-1\"),","            License(licenseKey: \"license-key-2\")","        ]","    )","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType"},{"type":"text","text":" for a full list of services, and read more about them in the "},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","isActive":true},{"type":"text","text":" article."}]},{"type":"paragraph","inlineContent":[{"text":"Once you have a license engine, you can use it to resolve licenses for your product, by letting users enter ","type":"text"},{"type":"emphasis","inlineContent":[{"type":"text","text":"their"}]},{"type":"text","text":" license keys:"}]},{"type":"codeListing","syntax":"swift","code":["do {","    let license = try await engine.getLicense(for: \"license-key-1\")","    \/\/ Do anything you want with the license","} catch {","    \/\/ Inform the user about the error","}"]},{"type":"paragraph","inlineContent":[{"text":"The engine will use the services you specified to retrieve the license, and validate any matching license for the current platform, product bundle & date. You can perform more validations after retrieving the license.","type":"text"}]},{"inlineContent":[{"text":"Once you have the license, it will provide you with a lot of information, and lets you validate things like tiers, features, etc. See ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","isActive":true},{"text":" for a full list of information & validation methods, and read more about the LicenseKit license model in ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","isActive":true,"type":"reference"},{"text":".","type":"text"}],"type":"paragraph"},{"text":"Apps vs. libraries","anchor":"Apps-vs-libraries","level":2,"type":"heading"},{"inlineContent":[{"text":"Licenses are handled a bit differently in apps and libraries.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"An app can create a license engine singleton when it launches, or whenever you need one. You can then provide a UI where your users can register their license key, using this engine.","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A library should provide a way for users to set up the library with their license key. You can then use this entry-point to create a license engine and validate the license key."}]},{"level":2,"text":"Pricing","anchor":"Pricing","type":"heading"},{"inlineContent":[{"type":"text","text":"LicenseKit requires a commercial license to be used. It’s free to start using and affordable to scale."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can purchase a license from the "},{"type":"reference","identifier":"https:\/\/kankoda.com\/licensekit","isActive":true},{"type":"text","text":" or use "},{"type":"codeVoice","code":"FREE"},{"type":"text","text":" as license key to use the library with a limited number of code- and file-based licenses and features."}],"type":"paragraph"},{"anchor":"Repository","type":"heading","text":"Repository","level":2},{"type":"paragraph","inlineContent":[{"text":"For more information, demo apps, issue tracking, etc., visit the ","type":"text"},{"isActive":true,"identifier":"https:\/\/github.com\/Kankoda\/LicenseKit","type":"reference"},{"text":".","type":"text"}]}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"],"anchor":"Articles","title":"Articles"},{"anchor":"Essentials","title":"Essentials","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType"]},{"title":"Integrations","anchor":"Integrations","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseIntegrations"]},{"generated":true,"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Swift"],"title":"Extended Modules","anchor":"Extended-Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/licensekit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/licensekit"]}],"metadata":{"roleHeading":"Framework","externalID":"LicenseKit","role":"collection","modules":[{"name":"LicenseKit"}],"title":"LicenseKit","symbolKind":"module"},"abstract":[{"text":"LicenseKit helps you protect your Swift-based software with commercial licenses.","type":"text"}],"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"title":"Understanding Licenses","kind":"article","url":"\/documentation\/licensekit\/understanding-licenses","abstract":[{"type":"text","text":"This article describes the LicenseKit license model."}],"type":"topic","role":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"},"Logo.png":{"variants":[{"url":"\/images\/com.licensekit.LicenseKit\/Logo.png","traits":["1x","light"]}],"type":"image","identifier":"Logo.png","alt":"LicenseKit logo"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Services":{"title":"Understanding License Services","kind":"article","url":"\/documentation\/licensekit\/understanding-license-services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"type":"topic","role":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Swift":{"url":"\/documentation\/licensekit\/swift","title":"Swift","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Swift","type":"topic","role":"collection"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"title":"LicenseKit","url":"\/documentation\/licensekit","kind":"symbol","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","role":"collection","abstract":[{"text":"LicenseKit helps you protect your Swift-based software with commercial licenses.","type":"text"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseKitVersionNumber":{"title":"LicenseKitVersionNumber","kind":"symbol","url":"\/documentation\/licensekit\/licensekitversionnumber","abstract":[{"type":"text","text":"Project version number for LicenseKit."}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"LicenseKitVersionNumber"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseKitVersionNumber"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"title":"License","navigatorTitle":[{"text":"License","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"License","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This struct represents a software license and also works"},{"text":" ","type":"text"},{"text":"as a namespace for license-related types.","type":"text"}],"url":"\/documentation\/licensekit\/license","kind":"symbol"},"https://github.com/Kankoda/LicenseKit":{"url":"https:\/\/github.com\/Kankoda\/LicenseKit","type":"link","identifier":"https:\/\/github.com\/Kankoda\/LicenseKit","title":"project repository","titleInlineContent":[{"type":"text","text":"project repository"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseKitVersionString":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseKitVersionString","fragments":[{"text":"LicenseKitVersionString","kind":"identifier"}],"type":"topic","abstract":[{"text":"Project version string for LicenseKit.","type":"text"}],"title":"LicenseKitVersionString","url":"\/documentation\/licensekit\/licensekitversionstring"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LicenseServiceType","kind":"identifier"}],"title":"LicenseServiceType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseServiceType"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","url":"\/documentation\/licensekit\/licenseservicetype","type":"topic","abstract":[{"type":"text","text":"This enum defines various license service types that can"},{"type":"text","text":" "},{"text":"be used to validate license keys and resolve licenses.","type":"text"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseIntegrations":{"role":"symbol","url":"\/documentation\/licensekit\/licenseintegrations","kind":"symbol","title":"LicenseIntegrations","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseIntegrations","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseIntegrations"}],"abstract":[{"text":"This namespace contains integration-related types.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LicenseIntegrations"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"url":"\/documentation\/licensekit\/licenseengine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"abstract":[{"text":"This is the most central class in LicenseKit and is used","type":"text"},{"type":"text","text":" "},{"text":"to validate license keys and return any matching license.","type":"text"}],"title":"LicenseEngine","navigatorTitle":[{"text":"LicenseEngine","kind":"identifier"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"topic","role":"symbol","kind":"symbol"},"https://kankoda.com/licensekit":{"url":"https:\/\/kankoda.com\/licensekit","type":"link","identifier":"https:\/\/kankoda.com\/licensekit","title":"LicenseKit website","titleInlineContent":[{"type":"text","text":"LicenseKit website"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFeature":{"title":"LicenseFeature","url":"\/documentation\/licensekit\/licensefeature","kind":"symbol","abstract":[{"text":"This protocol can be implemented by any type that should","type":"text"},{"type":"text","text":" "},{"type":"text","text":"be used as a license-based feature."}],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LicenseFeature"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature","navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"],"anchor":"Articles"},{"generated":true,"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseKitVersionNumber","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseKitVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"}],"traits":[{"interfaceLanguage":"occ"}]}]}