{"abstract":[{"text":"This article describes how to get started with LicenseKit.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"primaryContentSections":[{"content":[{"text":"License Engine","type":"heading","level":2,"anchor":"License-Engine"},{"type":"paragraph","inlineContent":[{"text":"With LicenseKit, your app or library should create a ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference","isActive":true},{"text":" with the license key you obtain when you ","type":"text"},{"identifier":"https:\/\/kankoda.com\/licensekit","type":"reference","isActive":true},{"text":", then define which ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","type":"reference","isActive":true},{"text":"(s) you want to use to use to fetch and validate customer licenses.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, this would create a license engine with two licenses that are compiled into your product and will be validated on-device:"}]},{"type":"codeListing","code":["let licenseEngine = try await LicenseEngine(","    licenseKey: \"your-license-key\",","    licenseService: { license in","        .binary(","            licenses: [","                License(licenseKey: \"license-key-1\", ...),","                License(licenseKey: \"license-key-2\", ...)","            ]","        )","    }",")"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"There are many service types to choose from, as described in ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services","isActive":true},{"text":". You can use define licenses with source code, parse a license from an encrypted file, integrate with Gumroad or any external API, etc.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Once your app\/SDK has a license engine instance, you can use ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine\/getLicense(withKey:)","isActive":true,"type":"reference"},{"text":" to resolve and validate customer licenses. The engine will perform a basic date and product validation, after which you can perform additional license validations.","type":"text"}]},{"text":"License Registration","type":"heading","level":2,"anchor":"License-Registration"},{"type":"paragraph","inlineContent":[{"text":"Your app\/SDK should provide a way for your customers to enter ","type":"text"},{"type":"emphasis","inlineContent":[{"text":"their","type":"text"}]},{"text":" license key. An app can have a UI\/screen, while an SDK can have a well-defined setup\/unlock function like this one:","type":"text"}]},{"type":"codeListing","code":["public final class MyLibrary {","","    \/\/ Place this kind of function in your library, where it makes sense. ","    \/\/ You don't need a license key when you use encrypted license files.","    public static func setupLibrary(","        withLicenseKey key: String? = nil","    ) async throws {","        let license = try await engine.getLicense(for: key)","        \/\/ If we get a license value, then the license is valid for the","        \/\/ current date, product, and platform. We can now perform more","        \/\/ validations, set up the app\/SDK using the license, store the","        \/\/ license for the current session, etc.","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The engine will retrieve licenses with the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType"},{"type":"text","text":" that you defined, then validate any matching license for the current date, bundle, and platform. You can perform more validations after getting a license, using its many validation functions."}]},{"text":"License Validation","type":"heading","level":2,"anchor":"License-Validation"},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference"},{"text":" will validate fetched licenses for the current date, bundle, and platform, and will throw a ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","type":"reference"},{"text":" if no license exists, or if any of these criterias doesn’t validate.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This means that any license that the engine returns hasn’t expired, and is valid for the current app\/library and platform. You can perform additional validations to ensure that the license meets any additional requirements.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"For instance, you can define one or several ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature","type":"reference","isActive":true},{"text":" and make sure that the customer license has access to those features:","type":"text"}]},{"type":"codeListing","code":["enum MyLibraryFeature: String, LicenseFeature {","","    case maps, weather, ...","","    var featureId: String? { rawValue }","","    var unlockedByTier: License.Tier? {","        switch self {","        case .maps: .silver","        case .weather: .gold","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can then validate these features when creating feature-related types, and throw a "},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","type":"reference","isActive":true},{"type":"text","text":" if the license doesn’t have the right to use that specific feature."}]},{"type":"paragraph","inlineContent":[{"text":"The code example below uses the current license that is stored in the ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseStore\/shared"},{"text":" license store, to validate various feature-based types.","type":"text"}]},{"type":"codeListing","code":["public extension License {","","    var current: License {","        \/\/ See \"License Store\" further down...","    }","}","","public class MyBasicFeature {","    public init() throws {","        try License.validate(.current)","    }","}","","public class MyMapsFeature {","    public init() throws {","        try License.validate(.current) { license in","            try license.validateFeature(MyLibraryFeature.maps)","        }","    }","}","","public class MyWeatherFeature {","    public init() throws {","        try License.validate(.current) { license in","            try license.validateFeature(MyLibraryFeature.weather)","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This means that you can make it impossible to create certain types in your library, while also making some types not require a license."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You should use "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validate(_:bundleId:date:platform:additionalValidation:)"},{"type":"text","text":" when validating customer licenses. This will throw an error if the provided license is nil, and lets you provide an additional validation block for valid licenses."}]},{"text":"License Store","type":"heading","level":2,"anchor":"License-Store"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Most apps and libraries will have a single user at a time, per running instance. For these cases, you can use a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseStore"},{"type":"text","text":" to store the current valid license in a thread-safe way."}]},{"type":"paragraph","inlineContent":[{"text":"You can create an internal or private license store for your app\/SDK, then add a ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","type":"reference","isActive":true},{"text":" extensions to easily fetch the current license:","type":"text"}]},{"type":"codeListing","code":["extension LicenseStore {","    static let myLibraryStore = LicenseStore()","}","","extension License {","    var current: License { ","        License.current(in: myLibraryStore)","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can inject the store into your ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference"},{"text":" to automatically store licenses that you receive with ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine\/getLicense(withKey:)","type":"reference"},{"text":":","type":"text"}]},{"type":"codeListing","code":["let myLibraryEngine = try await LicenseEngine(","    licenseKey: \"your-license-key\",","    licenseStore: .myLibraryStore,","    licenseService: { license in ... }",")"],"syntax":"swift"},{"content":[{"inlineContent":[{"text":"Make sure to keep your license store and license engine internal, to avoid that your users can access them and inject fake licenses.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important","name":"Important"},{"text":"Apps","type":"heading","level":2,"anchor":"Apps"},{"type":"paragraph","inlineContent":[{"text":"LicenseKit has SwiftUI Previews-based “apps” that can be used in your app\/SDK’s source code.","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"code":"LicenseManagerApp","type":"codeVoice"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"code":"LicenseFileDecryptorApp","type":"codeVoice"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A separate article will be created for this."}]},{"text":"Demo apps and inspiration","type":"heading","level":2,"anchor":"Demo-apps-and-inspiration"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Have a look at the demo app and demo library for examples on how to do this. LicenseKit doesn’t put any restrictions on how you use the "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":" or "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseStore"},{"type":"text","text":", but you can use these demos for inspiration."}]},{"text":"Further reading","type":"heading","level":2,"anchor":"Further-reading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"},{"type":"text","text":" article for more information about the LicenseKit "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" model, and the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"},{"type":"text","text":" article for more information about the available "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType"},{"type":"text","text":"s and how they work."}]}],"kind":"content"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"],"generated":true,"title":"Articles","anchor":"Articles"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/licensekit\/getting-started-article"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/licensekit\/getting-started-article"]}],"sections":[],"metadata":{"modules":[{"name":"LicenseKit"}],"role":"article","roleHeading":"Article","title":"Getting Started"},"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"url":"\/documentation\/licensekit\/understanding-licenses","kind":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","abstract":[{"text":"This article describes the LicenseKit license model.","type":"text"}],"type":"topic","title":"Understanding Licenses","role":"article"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Files":{"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files","title":"Understanding License Files","kind":"article","role":"article","url":"\/documentation\/licensekit\/understanding-license-files","abstract":[{"type":"text","text":"This article describes the LicenseKit license file engine."}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType":{"type":"topic","abstract":[{"type":"text","text":"This enum defines various license service types that can"},{"type":"text","text":" "},{"type":"text","text":"be used to validate license keys and resolve licenses."}],"title":"LicenseServiceType","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","kind":"symbol","role":"symbol","url":"\/documentation\/licensekit\/licenseservicetype","navigatorTitle":[{"text":"LicenseServiceType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseServiceType","kind":"identifier"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Services":{"kind":"article","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"title":"Understanding License Services","role":"article","url":"\/documentation\/licensekit\/understanding-services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"type":"topic","url":"\/documentation\/licensekit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"role":"collection","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","title":"LicenseKit","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"navigatorTitle":[{"kind":"identifier","text":"License"}],"abstract":[{"type":"text","text":"This struct represents a software license and also works"},{"type":"text","text":" "},{"type":"text","text":"as a namespace for license-related types."}],"url":"\/documentation\/licensekit\/license","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","title":"License","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/validate(_:bundleId:date:platform:additionalValidation:)":{"title":"validate(_:bundleId:date:platform:additionalValidation:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validate(_:bundleId:date:platform:additionalValidation:)","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate the provided license, if any."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V","text":"License"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"},{"kind":"text","text":", "},{"kind":"externalParam","text":"platform"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V8PlatformO","text":"Platform"},{"kind":"text","text":", "},{"kind":"externalParam","text":"additionalValidation"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V","text":"License"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/licensekit\/license\/validate(_:bundleid:date:platform:additionalvalidation:)"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","url":"\/documentation\/licensekit\/licenseengine","abstract":[{"type":"text","text":"This class is the most central type in LicenseKit and is"},{"type":"text","text":" "},{"type":"text","text":"used to fetch licenses using an injected license service."}],"title":"LicenseEngine"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine/getLicense(withKey:)":{"url":"\/documentation\/licensekit\/licenseengine\/getlicense(withkey:)","kind":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine\/getLicense(withKey:)","abstract":[{"text":"Try to register a license key for your product.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLicense","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"License","kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V"}],"type":"topic","title":"getLicense(withKey:)","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseStore":{"abstract":[{"text":"This actor can be used to store a single, active license.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseStore","url":"\/documentation\/licensekit\/licensestore","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseStore"}],"title":"LicenseStore","navigatorTitle":[{"kind":"identifier","text":"LicenseStore"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseStore/shared":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LicenseStore","preciseIdentifier":"s:10LicenseKit0A5StoreC","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/licensekit\/licensestore\/shared","abstract":[{"text":"A shared license store.","type":"text"}],"title":"shared","role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseStore\/shared"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFeature":{"url":"\/documentation\/licensekit\/licensefeature","role":"symbol","type":"topic","kind":"symbol","title":"LicenseFeature","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFeature","kind":"identifier"}],"navigatorTitle":[{"text":"LicenseFeature","kind":"identifier"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature","abstract":[{"text":"This protocol can be implemented by any type that should","type":"text"},{"text":" ","type":"text"},{"text":"be used as a license-based feature.","type":"text"}]},"https://kankoda.com/licensekit":{"url":"https:\/\/kankoda.com\/licensekit","identifier":"https:\/\/kankoda.com\/licensekit","titleInlineContent":[{"text":"sign up for LicenseKit","type":"text"}],"type":"link","title":"sign up for LicenseKit"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/ValidationError":{"url":"\/documentation\/licensekit\/license\/validationerror","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","role":"symbol","title":"License.ValidationError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"This enum defines license validation errors that can"},{"type":"text","text":" "},{"type":"text","text":"be thrown when a license key is validated."}],"navigatorTitle":[{"kind":"identifier","text":"ValidationError"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"]}]}],"traits":[{"interfaceLanguage":"occ"}]}]}