{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The main "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"},{"type":"text","text":" article has information on how to add LicenseKit to your project. Once you have installed it and linked it to your app target, you can import and start using it."}]},{"anchor":"How-to-setup-LicenseKit","level":2,"type":"heading","text":"How to setup LicenseKit"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In LicenseKit, a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":" is used to manage your product licenses. Use "},{"type":"emphasis","inlineContent":[{"type":"text","text":"your"}]},{"type":"text","text":" LicenseKit license key to create a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":", then define which license service to use."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here, we use the “FREE” LicenseKit license key to create an license engine that uses a "},{"type":"codeVoice","code":".binary"},{"type":"text","text":" service with hard-coded licenses:"}]},{"type":"codeListing","syntax":"swift","code":["let engine = try await LicenseEngine(licenseKey: \"Your license key\") {","    .binary(","        licenses: [","            License(licenseKey: \"license-key-1\"),","            License(licenseKey: \"license-key-2\")","        ]","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can choose from many different service types, such as "},{"type":"codeVoice","code":".binary"},{"type":"text","text":", "},{"type":"codeVoice","code":".file"},{"type":"text","text":", "},{"type":"codeVoice","code":".api"},{"type":"text","text":", "},{"type":"codeVoice","code":".gumroad"},{"type":"text","text":", "},{"type":"codeVoice","code":".cached"},{"type":"text","text":", and "},{"type":"codeVoice","code":".proxy"},{"type":"text","text":" to create a service configuration that suits your needs."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Read more about the various service types in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"},{"type":"text","text":", and see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"},{"type":"text","text":" for more information."}]},{"anchor":"How-to-resolve-licenses","level":2,"type":"heading","text":"How to resolve licenses"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once you have a license engine, you can use it to resolve licenses for your product:"}]},{"type":"codeListing","syntax":"swift","code":["let license = try await engine.getLicense(for: \"license-key-1\")"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The engine will use the service you specified to get the license, and will by default validate the license for the current platform, product bundle and date before returning it. You can perform more validations after retrieving the license."}]},{"anchor":"Apps-vs-libraries","level":2,"type":"heading","text":"Apps vs. libraries"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Licenses are handled a bit differently in apps and libraries."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In an "},{"type":"strong","inlineContent":[{"type":"text","text":"app"}]},{"type":"text","text":", you can create a license engine singleton when the app launches, or whenever you need it. You can then provide a UI where users can register their license key, using this engine."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In a "},{"type":"strong","inlineContent":[{"type":"text","text":"library"}]},{"type":"text","text":", you should provide a way for users to set up your library with their license key. You can then use this entry-point to create a license engine and validate the license key."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/licensekit\/getting-started"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/licensekit\/getting-started"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes how to get started with LicenseKit."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Getting started","role":"article","modules":[{"name":"LicenseKit"}]},"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors"],"generated":true}],"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Services":{"role":"article","title":"Understanding License Services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-license-services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"role":"collection","title":"LicenseKit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","kind":"symbol","type":"topic","url":"\/documentation\/licensekit"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Errors":{"role":"article","title":"Understanding License Errors","abstract":[{"type":"text","text":"This article describes the license error model and how to handle errors that are thrown."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-license-errors"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"role":"article","title":"Understanding Licenses","abstract":[{"type":"text","text":"This article describes the LicenseKit license model."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-licenses"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"role":"symbol","title":"LicenseEngine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"abstract":[{"type":"text","text":"This is the most central class in LicenseKit and is used to"},{"type":"text","text":" "},{"type":"text","text":"resolve license keys."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"url":"\/documentation\/licensekit\/licenseengine"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}