{"primaryContentSections":[{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"Overview"},{"inlineContent":[{"type":"text","text":"LicenseKit has many different service types, which are defined by the "},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","isActive":true,"type":"reference"},{"type":"text","text":" enum:"}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/api(configuration:cached:urlSession:licenseMapping:)","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/binary(licenses:)","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/cached(service:)","type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/fileName(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","type":"reference"}]}]},{"content":[{"inlineContent":[{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/fileUrl(fileUrl:componentSeparator:licenseMapping:)","type":"reference"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/gumroad(productId:cached:urlSession:licenseMapping:)","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/proxy(services:)","isActive":true,"type":"reference"}]}]}]},{"inlineContent":[{"text":"You can specify which service type(s) that you want to use when you create your ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","type":"reference","isActive":true},{"text":" instance.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"API licenses","anchor":"API-licenses"},{"inlineContent":[{"type":"text","text":"You can use an API service to fetch licenses from a remote Rest API. Connecting over the Internet means that the user must be online. You can use a cached license wrapper to cache successful license validations."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"To map licenses from a specific API, you must define a custom "},{"code":"Decodable","type":"codeVoice"},{"type":"text","text":" type that can decode a specific API response, for instance:"}],"type":"paragraph"},{"code":["struct ApiLicenseModel: Decodable {","","    let licenseKey: String","    let customerName: String","    let tier: String","","    var license: License {","        License(","            licenseKey: licenseKey,","            customer: .init(name: customerName)","            tier: .init(name: tier)","        )","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"This custom type would be able to map the following API response:","type":"text"}],"type":"paragraph"},{"code":["{","    \"licenseKey\": \"ABC123\",","    \"customerName\": \"Cool Company Ltd.\",","    \"expirationDate\": \"2027-01-31\"","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"You can then use an API service to fetch data, by providing a mapping function to decode the data and map it to a ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","isActive":true,"type":"reference"},{"text":":","type":"text"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"your-key\") {","    try .api(","        configuration: .init(","            url: { licenseKey in URL(string: \"https:\/\/myapi.com\/licenses\/\\(licenseKey)\")! },","            httpMethod: { licenseKey in \"POST\" },","            httpHeaders: { licenseKey in [\"api-token\": \"ejiwaogja=\"] }","        ),","        licenseMapping { data in","            let decoder = JSONDecoder()","            let response = try decoder.decode(ApiLicenseModel.self, from: data)","            License(licenseKey: response.licenseKey)","        }","    )","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"This way to provide a configuration and a mapping function lets you customize this service to great extent.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Binary licenses","anchor":"Binary-licenses"},{"inlineContent":[{"type":"text","text":"Binary licenses are hard-coded into your binary, using plain Swift code, and will be validated on-device. You can define binary licenses by creating static "},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","type":"reference"},{"type":"text","text":" values, for instance:"}],"type":"paragraph"},{"code":["extension License {","","    \/\/\/ A basic license that only defines a license key","    static let basicLicense = License(","        licenseKey: \"DCE54718-A214-40E7-B3E8-3C7B1967F485\")","","    \/\/\/ A license that defines customer, tier, features, etc:","    static let extensiveLicense = License(","        licenseKey: \"ABCDEFGH-IJKL-MNOP-QRST-UVWXYZ123456\"","        customer: .myCustomer,","        tier: .gold,","        expirationDate: Date(year: 2025, month: 01, day: 01),","        allowsExpiration: false,","        platforms: [.iOS, .tvOS],","        bundleIds: [\"com.customer.library\"]","    )","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"You can create collection extensions to define a convenient collection for all your binary licenses:","type":"text"}],"type":"paragraph"},{"code":["extension Collection where Element == License {","","    static var myProductLicenses: [License.Customer] {","        [.basicLicense, .extensiveLicense]","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"You can then setup your license engine with a binary service that uses your license collection:"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"...\") {","   try .binary(licenses: .myProductLicenses)","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Binary licenses are powerful, but require that you to release a new version of your software to add or remove licenses for your product."}],"type":"paragraph"},{"type":"heading","level":2,"text":"Cached licenses","anchor":"Cached-licenses"},{"inlineContent":[{"text":"You can use a cached license service to cache any license validation from any other license service. This makes it possible for a user to keep using your software even if the device is temporarily disconnected.","type":"text"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"your-key\") {","    try .cached(","        service: .gumroad(...)","    )","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Any license validations that fail due to a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError"},{"type":"text","text":" causes the cache to reset and the validation to fail with the original error."}],"type":"paragraph"},{"type":"heading","level":2,"text":"File licenses","anchor":"File-licenses"},{"inlineContent":[{"text":"File-based licenses are defined in files that are bundled with your product, for instance a “licenses.csv” file with a row for each license:","type":"text"}],"type":"paragraph"},{"code":["DCE54718-A214-40E7-B3E8-3C7B1967F485,Microsoft,BASIC,2023-10-01","ABCDEFGH-IJKL-MNOP-QRST-UVWXYZ123456,Apple,GOLD,2023-01-01","..."],"type":"codeListing","syntax":null},{"inlineContent":[{"type":"text","text":"You can then setup your license engine with a file-based service that uses your local license file:"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"...\") {","    try .file(","        fileName: \"licenses\",","        fileExtension: \"csv\",","        componentSeparator: \",\"","    ) { rows in","        rows.map {","            License(","                licenseKey: row[0],","                customer: .init(name: row[1])","                tier: .init(name: row[2])","            )","        }","    }","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"The code above parses a “licenses.csv” file in the main bundle, then maps every row to a license by using the first value as license key, the second as customer (company) name, and the third as license ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct","type":"reference","isActive":true},{"text":" (“basic”, “silver”, “enterprise”, etc.).","type":"text"}],"type":"paragraph"},{"inlineContent":[{"text":"License files are convenient, but require that you to release a new version of your software to add or remove licenses for your product.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Gumroad licenses","anchor":"Gumroad-licenses"},{"inlineContent":[{"text":"You can use a Gumroad service to fetch licenses from the Gumroad license API, and provide a license mapping function that maps the raw Gumroad response to a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"your-key\") {","    try .gumroad(","        productId: \"unique-product-id\",","        licenseMapping { response in","            var license = response.license","            \/\/ You can customize or replace this standard license here","            return license","        }","    )","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"text":"You can either just return the response’s standard license, customize or replace it, or map the raw responses in any way you want.","type":"text"}],"type":"paragraph"},{"type":"heading","level":2,"text":"Service Proxying","anchor":"Service-Proxying"},{"inlineContent":[{"type":"text","text":"You can use a service proxy to combine several services into a single one. This makes is possible to e.g. perform both code-, file- and api-based license validation with a single service, in the sequential order of the provided services."}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(licenseKey: \"your-key\") {","    try .proxy(","        services: [","            .binary(","                license: license,","                customerLicenses: .all","            ),","            try .gumroad(","                license: license,","                productId: \"unique-product-id\",","                licenseMapping { response in","                    ...","                }","            )","        ]","    )","}"],"type":"codeListing","syntax":"swift"},{"inlineContent":[{"type":"text","text":"Service proxies are needed to fetch licenses from multiple sources, for instance if you sell subscriptions on multiple platforms. You can apply a different "},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Source-swift.enum","isActive":true,"type":"reference"},{"type":"text","text":" to each service to determine from where a license originates."}],"type":"paragraph"}],"kind":"content"}],"kind":"article","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"variants":[{"paths":["\/documentation\/licensekit\/understanding-license-services"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/licensekit\/understanding-license-services"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"LicenseKit"}],"roleHeading":"Article","role":"article","title":"Understanding License Services"},"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"sections":[],"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"],"anchor":"Articles","title":"Articles","generated":true}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/gumroad(productId:cached:urlSession:licenseMapping:)":{"type":"topic","title":"LicenseServiceType.gumroad(productId:cached:urlSession:licenseMapping:)","abstract":[{"type":"text","text":"A Gumroad-based license service."}],"role":"symbol","kind":"symbol","url":"\/documentation\/licensekit\/licenseservicetype\/gumroad(productid:cached:urlsession:licensemapping:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/gumroad(productId:cached:urlSession:licenseMapping:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gumroad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Key","preciseIdentifier":"s:10LicenseKit0A0V3Keya"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"LicenseIntegrations","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Gumroad","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV7GumroadV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Purchase","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV7GumroadV8PurchaseV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":")"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType":{"kind":"symbol","navigatorTitle":[{"text":"LicenseServiceType","kind":"identifier"}],"url":"\/documentation\/licensekit\/licenseservicetype","type":"topic","title":"LicenseServiceType","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","abstract":[{"type":"text","text":"This enum defines various license service types that can"},{"type":"text","text":" "},{"type":"text","text":"be used to validate license keys and resolve licenses."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LicenseServiceType","kind":"identifier"}],"role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","title":"License","role":"symbol","navigatorTitle":[{"text":"License","kind":"identifier"}],"url":"\/documentation\/licensekit\/license","kind":"symbol","abstract":[{"text":"This struct represents a software license and also works","type":"text"},{"text":" ","type":"text"},{"text":"as a namespace for license-related types.","type":"text"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"License","kind":"identifier"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Tier-swift.struct":{"abstract":[{"type":"text","text":"This struct represents a license tier, which defines"},{"type":"text","text":" "},{"type":"text","text":"the level of service that a license provides."}],"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Tier"}],"navigatorTitle":[{"kind":"identifier","text":"Tier"}],"url":"\/documentation\/licensekit\/license\/tier-swift.struct","title":"License.Tier","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","url":"\/documentation\/licensekit","role":"collection","type":"topic","kind":"symbol","title":"LicenseKit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/proxy(services:)":{"role":"symbol","title":"LicenseServiceType.proxy(services:)","url":"\/documentation\/licensekit\/licenseservicetype\/proxy(services:)","abstract":[{"type":"text","text":"A license service proxy."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"proxy","kind":"identifier"},{"text":"(","kind":"text"},{"text":"services","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO","text":"LicenseServiceType","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/proxy(services:)","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/ValidationError":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationError","kind":"identifier"}],"url":"\/documentation\/licensekit\/license\/validationerror","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","abstract":[{"text":"This enum defines license validation errors that can","type":"text"},{"text":" ","type":"text"},{"text":"be thrown when a license key is validated.","type":"text"}],"title":"License.ValidationError","navigatorTitle":[{"text":"ValidationError","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/binary(licenses:)":{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/binary(licenses:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A binary license service."}],"kind":"symbol","url":"\/documentation\/licensekit\/licenseservicetype\/binary(licenses:)","title":"LicenseServiceType.binary(licenses:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenses","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"License","preciseIdentifier":"s:10LicenseKit0A0V","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/fileUrl(fileUrl:componentSeparator:licenseMapping:)":{"role":"symbol","title":"LicenseServiceType.fileUrl(fileUrl:componentSeparator:licenseMapping:)","url":"\/documentation\/licensekit\/licenseservicetype\/fileurl(fileurl:componentseparator:licensemapping:)","abstract":[{"type":"text","text":"A file-based license service."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fileUrl","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fileUrl","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"componentSeparator","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SJ","text":"Character","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"licenseMapping","kind":"externalParam"},{"text":": ([","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A0V","text":"License","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/fileUrl(fileUrl:componentSeparator:licenseMapping:)","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/fileName(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)":{"abstract":[{"type":"text","text":"A file-based license service."}],"title":"LicenseServiceType.fileName(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","url":"\/documentation\/licensekit\/licenseservicetype\/filename(filename:fileextension:bundle:componentseparator:licensemapping:)","kind":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/fileName(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileName"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileExtension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"componentSeparator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SJ","text":"Character"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V","text":"License"},{"kind":"text","text":")"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Source-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"Source"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"kind":"symbol","type":"topic","title":"License.Source","role":"symbol","url":"\/documentation\/licensekit\/license\/source-swift.enum","abstract":[{"text":"This enum defines various license sources from which","type":"text"},{"text":" ","type":"text"},{"text":"licenses can be read or fetched.","type":"text"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Source-swift.enum"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"title":"Understanding Licenses","abstract":[{"text":"This article describes the LicenseKit license model.","type":"text"}],"kind":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","role":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-licenses"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/cached(service:)":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cached","kind":"identifier"},{"text":"(","kind":"text"},{"text":"service","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"LicenseServiceType","kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO"},{"text":")","kind":"text"}],"title":"LicenseServiceType.cached(service:)","url":"\/documentation\/licensekit\/licenseservicetype\/cached(service:)","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/cached(service:)","abstract":[{"text":"A cached license service.","type":"text"}],"role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/api(configuration:cached:urlSession:licenseMapping:)":{"role":"symbol","title":"LicenseServiceType.api(configuration:cached:urlSession:licenseMapping:)","url":"\/documentation\/licensekit\/licenseservicetype\/api(configuration:cached:urlsession:licensemapping:)","abstract":[{"type":"text","text":"An API-based license service."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"api","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO16ApiConfigurationa","text":"ApiConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cached","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"urlSession","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"licenseMapping","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A0V","text":"License","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A0V3Keya","text":"Key","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A0V","text":"License","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/api(configuration:cached:urlSession:licenseMapping:)","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"navigatorTitle":[{"text":"LicenseEngine","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseEngine","kind":"identifier"}],"kind":"symbol","type":"topic","title":"LicenseEngine","role":"symbol","url":"\/documentation\/licensekit\/licenseengine","abstract":[{"type":"text","text":"This class is the most central type in LicenseKit and is"},{"type":"text","text":" "},{"type":"text","text":"used to fetch licenses using an injected license service."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"],"generated":true,"anchor":"Articles"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}