{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" represents a software license that can be resolved with a license key."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"LicenseKit licenses (see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses"},{"type":"text","text":") can specify and validate expiration date, platform, bundle ID, tier, environment, features, and much, much more."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"LicenseKit uses services (see "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"},{"type":"text","text":") to compile licenses into the product binary, read licenses from files, fetch licenses from remote APIs, integrate with external services like Gumroad, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"LicenseKit also lets you cache validation results to handle temporary connectivity loss, and use service proxying to use multiple services to validate license keys."}]},{"anchor":"License-Engine","level":2,"type":"heading","text":"License Engine"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In LicenseKit, you use a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":" to resolve product licenses. You can read about how to setup an engine in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The license engine uses services to fetch licenses, then perform an initial license validation to see that the license can be used with the software, that is hasn’t expired, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The license engine then returns any valid licenses to you, let you use them in any way you want."}]},{"anchor":"License-Validation","level":2,"type":"heading","text":"License Validation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" can validate a bunch of things, such as a standard "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validate()"},{"type":"text","text":" to check that the license is valid for the current bundle, platform and date, as well as "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validateBundle()"},{"type":"text","text":", "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validateTier(_:)"},{"type":"text","text":", and much more."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the license key or the retrieved license is invalid, the license engine will throw a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError"},{"type":"text","text":". LicenseKit uses the same logic to validate your license when you create a license engine with your license key."}]},{"anchor":"License-Information","level":2,"type":"heading","text":"License Information"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" contains a lot of optional information, such as the license key, the name of the product that uses it, activation and expiration dates, etc. Most info is optional, which means that you only have to provide what matters to you."}]},{"anchor":"Customers","level":3,"type":"heading","text":"Customers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"License\/Customer"},{"type":"text","text":" defines a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" owner and can define things like the customer name and address, contact details, etc."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"A convenient way to define customers is to create static values:"}]},{"type":"codeListing","syntax":"swift","code":["extension License.Customer {","","    static let apple = Self(","        name: \"Apple\",","        contact: \"John Appleseed\",","        email: \"john@apple.com\",","        website: \"https:\/\/apple.com\"","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can then refer to your customers when defining licenses, for instance:"}]},{"type":"codeListing","syntax":"swift","code":["extension License {","","    static let microsoftLicense = License(","        licenseKey: \"DCE54718-A214-40E7-B3E8-3C7B1967F485\",","        customer: .microsoft,","        tier: .gold,","        expirationDate: Date(year: 2025, month: 01, day: 01)","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can of course also just define the customer directly when defining the license, but the static approach is convenient if multiple licenses share a single customer."}]},{"anchor":"Tiers","level":3,"type":"heading","text":"Tiers"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A license tier defines the level of service that a specific "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" has access to."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"LicenseKit defined many standard tiers, like "},{"type":"codeVoice","code":".standard"},{"type":"text","text":", "},{"type":"codeVoice","code":".basic"},{"type":"text","text":", "},{"type":"codeVoice","code":".silver"},{"type":"text","text":" and "},{"type":"codeVoice","code":".gold"},{"type":"text","text":", and groups licenses together in conceptual "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/TierGroup"},{"type":"text","text":" groups that target certain business models."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can define custom tiers as well:"}]},{"type":"codeListing","syntax":"swift","code":["extension License.Tier {","","    static let everything = Self(","        id: \"com.mylibrary.license.everything\",","        name: \"The Everything Tier\",","        level: 1_000","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can then refer to your custom tier when defining licenses in code:"}]},{"type":"codeListing","syntax":"swift","code":["extension License {","","    static let myCustomerLicense = Self(","        licenseKey: \"DCE54718-A214-40E7-B3E8-3C7B1967F485\",","        customer: .microsoft,","        tier: .everything,","        expirationDate: Date(year: 2025, month: 01, day: 01)","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can make certain types or features require a certain license tier. For instance, this class requires at least a Silver tier:"}]},{"type":"codeListing","syntax":"swift","code":["class CoolFeature {","","    init(license: License) throws {","        try license.validateTier(.silver)","        self.locale = locale","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you try to create an instance of this class with a license that doesn’t have a proper tier, the validation will throw a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError"},{"type":"text","text":"."}]},{"anchor":"Platforms","level":3,"type":"heading","text":"Platforms"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Platform"},{"type":"text","text":" enum defines hardware platforms that a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" can be valid for. This means that you can have different license prices for the number of platforms a license supports."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, here we define a license that can only be used on iOS:"}]},{"type":"codeListing","syntax":"swift","code":["extension License {","","    static let myBasicCustomersLicense = License(","        licenseKey: \"38B386BD-0684-4A30-B9F5-527FFF15D9BE\",","        tier: .basic,","        platforms: [.iOS]","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you don’t specify a platform for a license, it will support all platforms."}]},{"anchor":"Environments","level":3,"type":"heading","text":"Environments"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Environment"},{"type":"text","text":" enum defines environments that a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" can be valid for. This means that you can have different license prices for the number of environments a license supports."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, here we define a license that can only be used in production:"}]},{"type":"codeListing","syntax":"swift","code":["extension License {","","    static let myBasicCustomersLicense = License(","        licenseKey: \"38B386BD-0684-4A30-B9F5-527FFF15D9BE\",","        tier: .basic,","        environments: [.production]","    )","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you don’t specify an environment for a license, it will support all platforms."}]},{"anchor":"Features","level":3,"type":"heading","text":"Features"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature"},{"type":"text","text":" protocol can be implemented by any type that can be unlocked with a license. This means that you can have different license prices for the number of features a license supports."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To define a license feature, just let any type implement the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature"},{"type":"text","text":" protocol and return an optional "},{"type":"codeVoice","code":"featureId"},{"type":"text","text":":"}]},{"type":"codeListing","syntax":"swift","code":["enum AppFeature: String, LicenseFeature {","    case .dictation","    case .localization","    ","    var featureId: String? { ","        switch self {","        case .dictation: return rawValue","        case .localization: return nil","        }","    }","","    var unlockedByTier: Tier? { .gold }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In the example above, only "},{"type":"codeVoice","code":".dictation"},{"type":"text","text":" case will be a protected feature, since "},{"type":"codeVoice","code":".localization"},{"type":"text","text":" doesn’t define a feature ID."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"We can now add this feature to any license that should have access to it:"}]},{"type":"codeListing","syntax":"swift","code":["var license1 = License(","    licenseKey: \"1\")","","var license2 = License(","    licenseKey: \"2\", ","    features: [AppFeature.dictation])","","var license3 = License(","    licenseKey: \"3\",","    tier: .gold)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"We can then validate if a license has access to a certain feature:"}]},{"type":"codeListing","syntax":"swift","code":["license1.validateFeature(AppFeature.dictation)    \/\/ False","license1.validateFeature(AppFeature.localization) \/\/ True","license2.validateFeature(AppFeature.dictation)    \/\/ True","license2.validateFeature(AppFeature.localization) \/\/ True","license3.validateFeature(AppFeature.dictation)    \/\/ True","license3.validateFeature(AppFeature.localization) \/\/ True"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Since "},{"type":"codeVoice","code":"AppFeature"},{"type":"text","text":" defines that it’s automatically unlocked by a "},{"type":"codeVoice","code":".gold"},{"type":"text","text":" tier, any license with a "},{"type":"codeVoice","code":".gold"},{"type":"text","text":" tier will automatically validate the feature as well."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can even make it impossible to create instances of a type that requires a certain feature, if the license lacks that feature:"}]},{"type":"codeListing","syntax":"swift","code":["class DictationService {","","    init(license: License) throws {","        try license.validateFeature(AppFeatures.dictation)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"If you try to create a instance with a license that lacks the "},{"type":"codeVoice","code":".dictation"},{"type":"text","text":" feature, the initializer will throw a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/licensekit\/understanding-licenses"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/licensekit\/understanding-licenses"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the LicenseKit license model."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Understanding Licenses","role":"article","modules":[{"name":"LicenseKit"}]},"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors"],"generated":true}],"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Services":{"role":"article","title":"Understanding License Services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-license-services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"role":"article","title":"Understanding Licenses","abstract":[{"type":"text","text":"This article describes the LicenseKit license model."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-licenses"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/validateBundle()":{"role":"symbol","title":"validateBundle()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateBundle"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Validate the license for the main bundle."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validateBundle()","kind":"symbol","type":"topic","url":"\/documentation\/licensekit\/license\/validatebundle()"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"role":"collection","title":"LicenseKit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","kind":"symbol","type":"topic","url":"\/documentation\/licensekit"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Environment":{"role":"symbol","title":"License.Environment","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Environment"}],"abstract":[{"type":"text","text":"This enum defines different types of environments where"},{"type":"text","text":" "},{"type":"text","text":"a license can be used."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Environment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Environment"}],"url":"\/documentation\/licensekit\/license\/environment"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/validateTier(_:)":{"role":"symbol","title":"validateTier(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateTier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Tier","preciseIdentifier":"s:10LicenseKit0A0V4TierV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Validate the license meets a certain tier."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validateTier(_:)","kind":"symbol","type":"topic","url":"\/documentation\/licensekit\/license\/validatetier(_:)"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"role":"symbol","title":"License","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}],"abstract":[{"type":"text","text":"This struct represents a software license and also works as"},{"type":"text","text":" "},{"type":"text","text":"a namespace for license-related types."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"License"}],"url":"\/documentation\/licensekit\/license"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Errors":{"role":"article","title":"Understanding License Errors","abstract":[{"type":"text","text":"This article describes the license error model and how to handle errors that are thrown."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-license-errors"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFeature":{"role":"symbol","title":"LicenseFeature","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseFeature"}],"abstract":[{"type":"text","text":"This protocol can be implemented by any type that should be"},{"type":"text","text":" "},{"type":"text","text":"used as a license-based feature."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFeature","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseFeature"}],"url":"\/documentation\/licensekit\/licensefeature"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Platform":{"role":"symbol","title":"License.Platform","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Platform"}],"abstract":[{"type":"text","text":"This enum specifies the various hardware platforms that"},{"type":"text","text":" "},{"type":"text","text":"a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" can be valid for."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Platform","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Platform"}],"url":"\/documentation\/licensekit\/license\/platform"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseError":{"role":"symbol","title":"LicenseError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseError"}],"abstract":[{"type":"text","text":"This enum defines various license errors that can be thrown"},{"type":"text","text":" "},{"type":"text","text":"when registering a license key or trying to access features"},{"type":"text","text":" "},{"type":"text","text":"that require a specific license type."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseError"}],"url":"\/documentation\/licensekit\/licenseerror"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/TierGroup":{"role":"symbol","title":"License.TierGroup","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TierGroup"}],"abstract":[{"type":"text","text":"A tier group defines tiers that go well together."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/TierGroup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TierGroup"}],"url":"\/documentation\/licensekit\/license\/tiergroup"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Getting-Started":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"This article describes how to get started with LicenseKit."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/licensekit\/getting-started"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"role":"symbol","title":"LicenseEngine","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"abstract":[{"type":"text","text":"This is the most central class in LicenseKit and is used to"},{"type":"text","text":" "},{"type":"text","text":"resolve license keys."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"url":"\/documentation\/licensekit\/licenseengine"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/validate()":{"role":"symbol","title":"validate()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Validate the license for the bundle, date & platform."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/validate()","kind":"symbol","type":"topic","url":"\/documentation\/licensekit\/license\/validate()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}