{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"},"abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"metadata":{"role":"article","roleHeading":"Article","modules":[{"name":"LicenseKit"}],"title":"Understanding License Services"},"variants":[{"paths":["\/documentation\/licensekit\/understanding-services"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/licensekit\/understanding-services"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"kind":"article","seeAlsoSections":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files"],"generated":true,"anchor":"Articles","title":"Articles"}],"sections":[],"primaryContentSections":[{"content":[{"type":"heading","level":2,"anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"LicenseKit has many different license service types, that can be used to manage licenses in different ways. You can for instance define licenses with code and compile them into your product, generate and parse encrypted files, integrate with any 3rd party API, etc."}]},{"type":"heading","level":2,"anchor":"Service-Types","text":"Service Types"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType"},{"type":"text","text":" enum defines all available service types:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/api(configuration:cached:urlSession:licenseMapping:)","isActive":true,"type":"reference"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/binary(licenses:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/cached(service:)","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/csvFile(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","isActive":true,"type":"reference"}]}]},{"content":[{"inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/csvFileUrl(_:componentSeparator:licenseMapping:)","type":"reference","isActive":true}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/encryptedFile(fileName:fileExtension:fileGenerator:fileBundle:)","type":"reference","isActive":true}]}]},{"content":[{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/gumroad(productId:cached:urlSession:licenseMapping:)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/proxy(services:)","isActive":true}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can specify which service type(s) to use when creating a "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":" instance, as described in "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article"},{"type":"text","text":". This article has examples for every license service type, sorted in alphabetic order."}]},{"type":"heading","level":3,"anchor":"%E2%98%81%EF%B8%8F-API-Integrations","text":"☁️ API Integrations"},{"type":"paragraph","inlineContent":[{"text":"You can use API license services to integrate with any Rest API, by making network requests and parsing API responses to a ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To map licenses from a specific API, you must define a custom "},{"type":"codeVoice","code":"Decodable"},{"type":"text","text":" type that can decode a specific API response, for instance:"}]},{"type":"codeListing","code":["struct MyApiLicense: Decodable {","","    let licenseKey: String","    let customerName: String","    let tier: String","","    var license: License {","        License(","            licenseKey: licenseKey,","            customer: .init(name: customerName)","            tier: .init(name: tier)","        )","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This type would be able to map the following response right away, and can define custom "},{"type":"codeVoice","code":"CodingKeys"},{"type":"text","text":" to support custom mappings:"}]},{"code":["{","    \"licenseKey\": \"ABC123\",","    \"tier\": \"gold\",","    \"customerName\": \"Cool Company Ltd.\"","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"You can now setup an API service with an API-specific config and a mapping function that decodes data and maps it to a ","type":"text"},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","type":"reference","isActive":true},{"text":":","type":"text"}],"type":"paragraph"},{"code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    try .api(","        configuration: .init(","            url: { licenseKey in URL(string: \"https:\/\/myapi.com\/licenses\/\\(licenseKey)\")! },","            httpMethod: { _ in \"POST\" },","            httpHeaders: { _ in [\"api-token\": \"ejiwaogja=\"] }","        ),","        licenseMapping { data in","            let decoder = JSONDecoder()","            let apiLicense = try decoder.decode(MyApiLicenseModel.self, from: data)","            return apiLicense.license","        }","    )","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"This way to provide an API-specific configuration and mapping function lets you customize this general API service to great extent.","type":"text"}],"type":"paragraph"},{"level":3,"anchor":"%F0%9F%93%A6-Binary-Licenses","type":"heading","text":"📦 Binary Licenses"},{"inlineContent":[{"text":"Binary licenses are defined with source code that is hard-coded into your binary and validated on-device. You can define licenses by creating static ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"text":" values, for instance:","type":"text"}],"type":"paragraph"},{"code":["extension License {","","    \/\/\/ A basic license that only defines a license key","    static let basicLicense = License(","        licenseKey: \"DCE54718-A214-40E7-B3E8-3C7B1967F485\")","","    \/\/\/ A license that defines more information:","    static let extensiveLicense = License(","        licenseKey: \"ABCDEFGH-IJKL-MNOP-QRST-UVWXYZ123456\"","        tier: .gold,","        expirationDate: Date(year: 2025, month: 01, day: 01),","        platforms: [.iOS, .tvOS],","        bundleIds: [\"com.customer.library\"]","    )","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"type":"text","text":"You can create license collections to define convenient access to your binary licenses, then setup a license engine with these licenses:"}],"type":"paragraph"},{"code":["extension Collection where Element == License {","","    static var myLicenses: [License.Customer] {","        [.basicLicense, .extensiveLicense]","    }","}","","let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .binary(licenses: .myLicenses)","}"],"syntax":"swift","type":"codeListing"},{"inlineContent":[{"text":"Binary licenses are powerful, but require that you to release a new version of your software to add or remove licenses for your product.","type":"text"}],"type":"paragraph"},{"type":"heading","level":3,"anchor":"%F0%9F%97%84%EF%B8%8F-Cached-Service","text":"🗄️ Cached Service"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use a cached license service to cache any license validation from any other license service. This makes it possible for a user to keep using your software even if the device is temporarily disconnected."}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .cached(","        service: .gumroad(...)","    )","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Any license validations that fail due to a "},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","type":"reference","isActive":true},{"type":"text","text":" causes the cache to reset and the validation to fail with the original error."}]},{"type":"heading","level":3,"anchor":"%F0%9F%93%84-CSV-License-Files","text":"📄 CSV License Files"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use a CSV license service to parse licenses that are defined in files that are either bundled with your product or fetched from any available URL, where each row defines a license:"}]},{"type":"codeListing","code":["DCE54718-A214-40E7-B3E8-3C7B1967F485,Microsoft,BASIC,2023-10-01","ABCDEFGH-IJKL-MNOP-QRST-UVWXYZ123456,Apple,GOLD,2023-01-01","..."],"syntax":null},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can then setup your license engine with a file-based service that uses your local license file:"}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .csvFile(","        fileName: \"licenses\",","        fileExtension: \"csv\",","        bundle: ..., \/\/ .main (app), .module (.package), or custom for binary.","        componentSeparator: \",\"","    ) { rows in","        rows.map {","            License(","                licenseKey: row[0],","                customer: .init(name: row[1])","                tier: .init(name: row[2])","            )","        }","    }","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The code above parses a license file by mapping each row to a license by using the first value as license key, the second as customer (company) name, and the third as license "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct"},{"type":"text","text":" (“basic”, “silver”, “enterprise”, etc.)."}]},{"type":"heading","level":3,"anchor":"%F0%9F%94%90-Encrypted-License-Files","text":"🔐 Encrypted License Files"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator"},{"type":"text","text":" to generate encrypted license files, then use an encrypted file service to parse these files:"}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .encryptedFile(","        fileName: \"MyLibrary\",","        fileExtension: \"license\",","        generator: .myLicenseFileGenerator(for: engineLicense)","    )","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"See "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files"},{"type":"text","text":" for more information on how to create a unique encryption key and file generator for your app\/SDK."}]},{"type":"heading","level":3,"anchor":"%F0%9F%8C%A9%EF%B8%8F-Gumroad-Integrations","text":"🌩️ Gumroad Integrations"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use a Gumroad license service to integrate with the Gumroad license API. It will automatically map Gumroad purchase data to a license, and lets you provide a custom license mapping function that maps the raw Gumroad response to a "},{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","isActive":true,"type":"reference"},{"type":"text","text":":"}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .gumroad(","        productId: \"unique-product-id\",","        licenseMapping: { response in","            var license = response.license","            \/\/ You can customize or replace this standard license here","            return license","        }","    )","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"text":"You can either just return the response’s original license, customize or replace the license, or handle the response in any way you want.","type":"text"}]},{"type":"heading","level":3,"anchor":"%F0%9F%94%80-Proxy-Services","text":"🔀 Proxy Services"},{"type":"paragraph","inlineContent":[{"text":"You can use a proxy service to combine several license services into a single service. This makes is possible to e.g. perform both binary, file, and api-based license validation with a single service, in the sequential order of the provided services.","type":"text"}]},{"type":"codeListing","code":["let engine = try await LicenseEngine(","    licenseKey: \"your-licensekit-license-key\"",") { engineLicense in","    .proxy(","        services: [","            .binary(...),","            .gumroad(...)","        ]","    )","}"],"syntax":"swift"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Service proxies are needed to fetch licenses from multiple sources, for instance if you sell subscriptions on multiple platforms. You can apply a different "},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Source-swift.enum","isActive":true},{"type":"text","text":" to each service to determine from where a license originates."}]}],"kind":"content"}],"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/binary(licenses:)":{"abstract":[{"text":"A binary license service.","type":"text"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/binary(licenses:)","url":"\/documentation\/licensekit\/licenseservicetype\/binary(licenses:)","title":"LicenseServiceType.binary(licenses:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"binary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenses","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:10LicenseKit0A0V","text":"License","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Tier-swift.struct":{"role":"symbol","title":"License.Tier","url":"\/documentation\/licensekit\/license\/tier-swift.struct","kind":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct","navigatorTitle":[{"text":"Tier","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Tier","kind":"identifier"}],"type":"topic","abstract":[{"text":"This struct represents a license tier, which defines","type":"text"},{"text":" ","type":"text"},{"text":"the level of service that a license provides.","type":"text"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFileGenerator":{"navigatorTitle":[{"text":"LicenseFileGenerator","kind":"identifier"}],"title":"LicenseFileGenerator","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator","kind":"symbol","url":"\/documentation\/licensekit\/licensefilegenerator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFileGenerator","kind":"identifier"}],"abstract":[{"text":"This license file generator can generate encrypted files","type":"text"},{"text":" ","type":"text"},{"text":"that can later be decrypted with encrypted file services.","type":"text"}],"type":"topic"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/cached(service:)":{"abstract":[{"text":"A cached license service.","type":"text"}],"title":"LicenseServiceType.cached(service:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/cached(service:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cached"},{"kind":"text","text":"("},{"kind":"externalParam","text":"service"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LicenseServiceType","preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO"},{"kind":"text","text":")"}],"url":"\/documentation\/licensekit\/licenseservicetype\/cached(service:)","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/csvFileUrl(_:componentSeparator:licenseMapping:)":{"abstract":[{"text":"A CSV file license service.","type":"text"}],"title":"LicenseServiceType.csvFileUrl(_:componentSeparator:licenseMapping:)","kind":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/csvFileUrl(_:componentSeparator:licenseMapping:)","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"csvFileUrl"},{"kind":"text","text":"("},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"kind":"externalParam","text":"componentSeparator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SJ","kind":"typeIdentifier","text":"Character"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": (["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10LicenseKit0A0V","kind":"typeIdentifier","text":"License"},{"kind":"text","text":")"}],"url":"\/documentation\/licensekit\/licenseservicetype\/csvfileurl(_:componentseparator:licensemapping:)","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Files":{"type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files","title":"Understanding License Files","kind":"article","role":"article","url":"\/documentation\/licensekit\/understanding-license-files","abstract":[{"type":"text","text":"This article describes the LicenseKit license file engine."}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/proxy(services:)":{"title":"LicenseServiceType.proxy(services:)","kind":"symbol","abstract":[{"text":"A license service proxy.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proxy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"services"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO","text":"LicenseServiceType"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/proxy(services:)","url":"\/documentation\/licensekit\/licenseservicetype\/proxy(services:)","type":"topic","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/csvFile(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"csvFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileExtension"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"Bundle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"componentSeparator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SJ","text":"Character"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10LicenseKit0A0V","text":"License"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A CSV file license service."}],"url":"\/documentation\/licensekit\/licenseservicetype\/csvfile(filename:fileextension:bundle:componentseparator:licensemapping:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/csvFile(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","kind":"symbol","title":"LicenseServiceType.csvFile(fileName:fileExtension:bundle:componentSeparator:licenseMapping:)","type":"topic","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"type":"topic","url":"\/documentation\/licensekit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"role":"collection","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","title":"LicenseKit","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Source-swift.enum":{"title":"License.Source","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Source"}],"abstract":[{"type":"text","text":"This enum defines various license sources from which"},{"type":"text","text":" "},{"type":"text","text":"licenses can be read or fetched."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Source"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Source-swift.enum","url":"\/documentation\/licensekit\/license\/source-swift.enum","type":"topic"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"url":"\/documentation\/licensekit\/understanding-licenses","kind":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","abstract":[{"text":"This article describes the LicenseKit license model.","type":"text"}],"type":"topic","title":"Understanding Licenses","role":"article"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"navigatorTitle":[{"kind":"identifier","text":"License"}],"abstract":[{"type":"text","text":"This struct represents a software license and also works"},{"type":"text","text":" "},{"type":"text","text":"as a namespace for license-related types."}],"url":"\/documentation\/licensekit\/license","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","title":"License","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Getting-Started-Article":{"role":"article","url":"\/documentation\/licensekit\/getting-started-article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","type":"topic","abstract":[{"type":"text","text":"This article describes how to get started with LicenseKit."}],"kind":"article","title":"Getting Started"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType":{"type":"topic","abstract":[{"type":"text","text":"This enum defines various license service types that can"},{"type":"text","text":" "},{"type":"text","text":"be used to validate license keys and resolve licenses."}],"title":"LicenseServiceType","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType","kind":"symbol","role":"symbol","url":"\/documentation\/licensekit\/licenseservicetype","navigatorTitle":[{"text":"LicenseServiceType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseServiceType","kind":"identifier"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","url":"\/documentation\/licensekit\/licenseengine","abstract":[{"type":"text","text":"This class is the most central type in LicenseKit and is"},{"type":"text","text":" "},{"type":"text","text":"used to fetch licenses using an injected license service."}],"title":"LicenseEngine"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/ValidationError":{"url":"\/documentation\/licensekit\/license\/validationerror","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/ValidationError","role":"symbol","title":"License.ValidationError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationError"}],"abstract":[{"type":"text","text":"This enum defines license validation errors that can"},{"type":"text","text":" "},{"type":"text","text":"be thrown when a license key is validated."}],"navigatorTitle":[{"kind":"identifier","text":"ValidationError"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/api(configuration:cached:urlSession:licenseMapping:)":{"abstract":[{"text":"An API-based license service.","type":"text"}],"title":"LicenseServiceType.api(configuration:cached:urlSession:licenseMapping:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/api(configuration:cached:urlSession:licenseMapping:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"api"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApiConfiguration","preciseIdentifier":"s:10LicenseKit0A11ServiceTypeO16ApiConfigurationa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Key","preciseIdentifier":"s:10LicenseKit0A0V3Keya"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":")"}],"url":"\/documentation\/licensekit\/licenseservicetype\/api(configuration:cached:urlsession:licensemapping:)","role":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/encryptedFile(fileName:fileExtension:fileGenerator:fileBundle:)":{"kind":"symbol","abstract":[{"type":"text","text":"An encrypted file-based license service."}],"role":"symbol","type":"topic","url":"\/documentation\/licensekit\/licenseservicetype\/encryptedfile(filename:fileextension:filegenerator:filebundle:)","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/encryptedFile(fileName:fileExtension:fileGenerator:fileBundle:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"encryptedFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileExtension"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileGenerator"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10LicenseKit0A13FileGeneratorC","kind":"typeIdentifier","text":"LicenseFileGenerator"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileBundle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"},{"kind":"text","text":")"}],"title":"LicenseServiceType.encryptedFile(fileName:fileExtension:fileGenerator:fileBundle:)"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseServiceType/gumroad(productId:cached:urlSession:licenseMapping:)":{"title":"LicenseServiceType.gumroad(productId:cached:urlSession:licenseMapping:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Gumroad-based license service."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"gumroad"},{"kind":"text","text":"("},{"kind":"externalParam","text":"productId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"urlSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"licenseMapping"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Key","preciseIdentifier":"s:10LicenseKit0A0V3Keya"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"LicenseIntegrations","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Gumroad","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV7GumroadV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Purchase","preciseIdentifier":"s:10LicenseKit0A12IntegrationsV7GumroadV8PurchaseV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"License","preciseIdentifier":"s:10LicenseKit0A0V"},{"kind":"text","text":")"}],"url":"\/documentation\/licensekit\/licenseservicetype\/gumroad(productid:cached:urlsession:licensemapping:)","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseServiceType\/gumroad(productId:cached:urlSession:licenseMapping:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files"],"generated":true,"anchor":"Articles","title":"Articles"}],"op":"replace","path":"\/seeAlsoSections"}],"traits":[{"interfaceLanguage":"occ"}]}]}