{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError"},{"type":"text","text":" enum defines errors that can be thrown when handling a license key or trying to access license-based features."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"License key-based operations can fail for a number of reasons. For instance, the license key may have expired or may refer to a license that doesn’t support the current platform or bundle."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"License errors should be handled differently based on if you are using LicenseKit in a library or an app."}]},{"anchor":"How-to-handle-license-errors-in-libraries","level":2,"type":"heading","text":"How to handle license errors in libraries"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Let’s imagine that you’re using LicenseKit in a library that has a function to set up the library with a customer license key:"}]},{"type":"codeListing","syntax":"swift","code":["public class MyLibrary {","","    private static let engine: LicenseEngine!","","    private static let license: License?","","    ...","","    static func setup(withLicenseKey key: String) async throws {","","        \/\/ This will only work if LicenseKit has this active license key","        engine = try await LicenseEngine(licenseKey: \"library-license-key\") {","            .binary(","                customerLicenses: [","                    License(licenseKey: \"customer-license-key\")","                ]","            )","        }","","        \/\/ This will only work if the provided key is \"customer-license-key\"","        license = try await engine.getLicense(withKey: key)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"In this case, you don’t have to handle license errors, since you can just throw the error and let your users handle it as they see fit."}]},{"anchor":"How-to-handle-license-errors-in-apps","level":2,"type":"heading","text":"How to handle license errors in apps"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Now, let’s imagine that you’re using LicenseKit in an app that uses licenses instead of in-app purchases or subscriptions and has a screen in which users can enter a license key and tap a button to register the license:"}]},{"type":"codeListing","syntax":"swift","code":["struct LicenseScreen: View {","","    init(","        licenseEngine: LicenseEngine = MyApp.licenseEngine","    ) {","        self.licenseEngine = licenseEngine","    }","","    private let licenseEngine: LicenseEngine","","    @State","    private var key = \"\"","","    @State","    private var license: License?","","    var body: some View {","        TextField(text: $key)","        Button(\"Register license key\") {","            registerLicenseKey(key)","        }","    }","","    func registerLicenseKey(_ key: String) {","        Task { @MainActor in","            do {","                self.license = try await licenseEngine.getLicense(withKey: key)","            } catch {","                \/\/ Handle the error","            }","        }","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here, you should should display the error in some way, to let the user know that the license key operation has failed."}]},{"anchor":"How-to-throw-license-errors-from-your-own-code","level":2,"type":"heading","text":"How to throw license errors from your own code"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use also LicenseKit to validate whether or not a license should give access to certain features or not."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For instance, this feature requires that "},{"type":"emphasis","inlineContent":[{"type":"text","text":"your"}]},{"type":"text","text":" user has has a "},{"type":"codeVoice","code":".gold"},{"type":"text","text":" tier license or greater:"}]},{"type":"codeListing","syntax":"swift","code":["class ProFeature {","","    static let requiredTier = LicenseTier.gold","","    override init(license: License) throws {","        license.validateTier(requiredTier)","    }","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This means that you can protect entire features within your own product, and throw license errors when a feature can’t be accessed."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/licensekit\/understanding-license-errors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/licensekit\/understanding-license-errors"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Errors","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This article describes the license error model and how to handle errors that are thrown."}],"kind":"article","metadata":{"roleHeading":"Article","title":"Understanding License Errors","role":"article","modules":[{"name":"LicenseKit"}]},"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"],"generated":true}],"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"role":"collection","title":"LicenseKit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","kind":"symbol","type":"topic","url":"\/documentation\/licensekit"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-License-Services":{"role":"article","title":"Understanding License Services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-license-services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Getting-Started":{"role":"article","title":"Getting started","abstract":[{"type":"text","text":"This article describes how to get started with LicenseKit."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/licensekit\/getting-started"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseError":{"role":"symbol","title":"LicenseError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseError"}],"abstract":[{"type":"text","text":"This enum defines various license errors that can be thrown"},{"type":"text","text":" "},{"type":"text","text":"when registering a license key or trying to access features"},{"type":"text","text":" "},{"type":"text","text":"that require a specific license type."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LicenseError"}],"url":"\/documentation\/licensekit\/licenseerror"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"role":"article","title":"Understanding Licenses","abstract":[{"type":"text","text":"This article describes the LicenseKit license model."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","kind":"article","type":"topic","url":"\/documentation\/licensekit\/understanding-licenses"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Services"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}