{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/licensekit\/understanding-license-files"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/licensekit\/understanding-license-files"]}],"metadata":{"modules":[{"name":"LicenseKit"}],"roleHeading":"Article","role":"article","title":"Understanding License Files"},"kind":"article","primaryContentSections":[{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"Overview"},{"inlineContent":[{"text":"LicenseKit can use a ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator","isActive":true},{"text":" to generate encrypted license files, then a ","type":"text"},{"type":"codeVoice","code":"LicenseServiceType\/encryptedFile(fileName:fileExtension:generator:bundle:)"},{"text":" license service to parse any file with the same generator.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"Encrypted license files make it easy for you to distribute licenses to your customers, that can be added to their product and validated on-device, without the need for network-based validation or for having to create new product versions to activate new licenses."}],"type":"paragraph"},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You need a "},{"isActive":true,"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct\/business","type":"reference"},{"type":"text","text":" license to be able to create and parse encrypted license files."}]}]},{"level":2,"type":"heading","text":"How to create a unique license file generator","anchor":"How-to-create-a-unique-license-file-generator"},{"inlineContent":[{"text":"To create a unique ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator","isActive":true},{"text":" for your app\/SDK, you must first generate a unique encryption key. You can do this by calling the static ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator\/generateUniqueEncryptionKey()","isActive":true},{"text":" function and storing the result.","type":"text"}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"You can then create a unique license file generator for your app\/SDK by passing in the generated key into the initializer, together with a "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License"},{"type":"text","text":" that you get when setting up your "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine"},{"type":"text","text":", as described in "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article"},{"type":"text","text":":"}],"type":"paragraph"},{"type":"codeListing","syntax":"swift","code":["extension LicenseFileGenerator {","","    static func myLicenseFileGenerator(","        for license: License","    ) throws -> LicenseFileGenerator {","        LicenseFileGenerator(","            license: license, ","            key: \"your-unique-encryption-key\"","        )","    }","} "]},{"style":"important","type":"aside","name":"Important","content":[{"type":"paragraph","inlineContent":[{"text":"Make sure to keep your unique encryption key private, since it can otherwise be used to tamper with your generated license files!","type":"text"}]}]}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"],"title":"Articles","generated":true,"anchor":"Articles"}],"identifier":{"url":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-License-Files","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit"]]},"sections":[],"abstract":[{"text":"This article describes the LicenseKit license file engine.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Licenses":{"url":"\/documentation\/licensekit\/understanding-licenses","kind":"article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","abstract":[{"text":"This article describes the LicenseKit license model.","type":"text"}],"type":"topic","title":"Understanding Licenses","role":"article"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFileGenerator/generateUniqueEncryptionKey()":{"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator\/generateUniqueEncryptionKey()","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generateUniqueEncryptionKey"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/licensekit\/licensefilegenerator\/generateuniqueencryptionkey()","abstract":[{"type":"text","text":"Generate a unique, private encryption key, which can"},{"type":"text","text":" "},{"type":"text","text":"be used to encrypt and decrypt license files."}],"role":"symbol","title":"generateUniqueEncryptionKey()"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit":{"type":"topic","url":"\/documentation\/licensekit","abstract":[{"type":"text","text":"LicenseKit helps you protect your Swift-based software with commercial licenses."}],"role":"collection","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit","title":"LicenseKit","kind":"symbol"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseEngine":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LicenseEngine"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LicenseEngine"}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseEngine","url":"\/documentation\/licensekit\/licenseengine","abstract":[{"type":"text","text":"This class is the most central type in LicenseKit and is"},{"type":"text","text":" "},{"type":"text","text":"used to fetch licenses using an injected license service."}],"title":"LicenseEngine"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License":{"navigatorTitle":[{"kind":"identifier","text":"License"}],"abstract":[{"type":"text","text":"This struct represents a software license and also works"},{"type":"text","text":" "},{"type":"text","text":"as a namespace for license-related types."}],"url":"\/documentation\/licensekit\/license","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License","title":"License","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"License"}]},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/License/Tier-swift.struct/business":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"business","kind":"identifier"},{"text":": `Self`","kind":"text"}],"url":"\/documentation\/licensekit\/license\/tier-swift.struct\/business","kind":"symbol","abstract":[{"type":"text","text":"An business tier with level of "},{"type":"codeVoice","code":"2"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/License\/Tier-swift.struct\/business","role":"symbol","title":"business"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Understanding-Services":{"kind":"article","type":"topic","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services","abstract":[{"type":"text","text":"This article describes the LicenseKit license service model and how to define and validate licenses."}],"title":"Understanding License Services","role":"article","url":"\/documentation\/licensekit\/understanding-services"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/LicenseFileGenerator":{"navigatorTitle":[{"text":"LicenseFileGenerator","kind":"identifier"}],"title":"LicenseFileGenerator","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/LicenseFileGenerator","kind":"symbol","url":"\/documentation\/licensekit\/licensefilegenerator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LicenseFileGenerator","kind":"identifier"}],"abstract":[{"text":"This license file generator can generate encrypted files","type":"text"},{"text":" ","type":"text"},{"text":"that can later be decrypted with encrypted file services.","type":"text"}],"type":"topic"},"doc://com.licensekit.LicenseKit/documentation/LicenseKit/Getting-Started-Article":{"role":"article","url":"\/documentation\/licensekit\/getting-started-article","identifier":"doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","type":"topic","abstract":[{"type":"text","text":"This article describes how to get started with LicenseKit."}],"kind":"article","title":"Getting Started"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Getting-Started-Article","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Licenses","doc:\/\/com.licensekit.LicenseKit\/documentation\/LicenseKit\/Understanding-Services"],"generated":true,"anchor":"Articles","title":"Articles"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}